import { LitElement, html } from "lit";
import { customElement, state } from "lit/decorators.js";

interface TutorialChapter {
  id: number;
  title: string;
  duration: string;
  description: string;
  steps: string[];
}

const CHAPTERS: TutorialChapter[] = [
  {
    id: 1,
    title: "Basic Movement & Territory",
    duration: "2 min",
    description: "Learn how to claim territory and expand your empire.",
    steps: [
      "Click any tile adjacent to your starting territory to attack it.",
      "Hold the attack button to send all available troops.",
      "Territory generates troops over time — expand to generate more.",
      "Your borders glow in your chosen color.",
    ],
  },
  {
    id: 2,
    title: "Economy & Resources",
    duration: "3 min",
    description: "Gold, Production, and Energy are the three pillars of your empire.",
    steps: [
      "Gold is generated by cities and trade routes. Spend it on research and diplomacy.",
      "Production comes from factories and ports. It trains your units.",
      "Energy comes from power plants. Running low makes advanced units go dormant.",
      "Check your resource bar at the top of the screen at all times.",
    ],
  },
  {
    id: 3,
    title: "Alliances & Diplomacy",
    duration: "3 min",
    description: "Allies win wars. Betrayal wins empires.",
    steps: [
      "Click another player's territory to open the diplomacy menu.",
      "Propose a Ceasefire to pause conflict for a set number of ticks.",
      "Form an Alliance for shared border defense.",
      "Breaking a ceasefire earns you a Warmonger badge — other players will trust you less.",
    ],
  },
  {
    id: 4,
    title: "Units & Combat",
    duration: "4 min",
    description: "Infantry is just the beginning. Build a combined-arms army.",
    steps: [
      "Infantry — cheap, fast, general purpose. Your bread and butter.",
      "Tanks — high attack, slow movement. Costs 3x infantry.",
      "Artillery — attacks 2 tiles away but cannot move while firing.",
      "Scouts — 2x movement speed and extended fog of war reveal.",
      "Medics heal nearby allied units each tick. Keep them behind the front line.",
      "Engineers build fortifications and supply hubs. Critical for long campaigns.",
    ],
  },
  {
    id: 5,
    title: "Tech Tree & Doctrine",
    duration: "4 min",
    description: "Research unlocks powerful permanent advantages.",
    steps: [
      "Open the Tech Panel from the left sidebar.",
      "Each technology takes ticks to research — only one at a time.",
      "Before the match starts, choose your Military Doctrine — it cannot be changed.",
      "Mass Assault: cheap infantry, huge armies. Superior Firepower: elite damage dealers.",
      "Mobile Warfare: fast strikes. Grand Battle Plan: slow but devastating planned offensives.",
    ],
  },
  {
    id: 6,
    title: "Special Abilities",
    duration: "3 min",
    description: "Five powerful abilities can turn the tide of battle.",
    steps: [
      "Abilities appear in the bar at the bottom of your screen.",
      "Blitz: all troops move 2x speed for 15 seconds. Perfect for breakthrough attacks.",
      "Fortify: +100% defense on selected territory for 30 seconds.",
      "Air Strike: area damage on a targeted tile. Use on packed enemy clusters.",
      "Propaganda: instantly converts 1 neutral or weakly-held border tile.",
      "Spy: reveals one enemy player's full resource count for 60 seconds.",
    ],
  },
  {
    id: 7,
    title: "HOI4 Systems — Focus Tree, Supply, Air",
    duration: "5 min",
    description: "The deep strategy layer that separates amateurs from conquerors.",
    steps: [
      "National Focus Tree: unlock permanent bonuses by spending Political Power.",
      "Focuses take game ticks to complete. Only one active at a time.",
      "Supply Lines: territory more than 8 hops from your capital fights at reduced power.",
      "Engineers build Supply Hubs to extend your supply reach.",
      "Air Wings cost Production to build. Assign missions: Air Superiority, Bombing, Close Air Support, Recon.",
      "Intelligence Agents cost Gold. Send them on missions to sabotage or steal enemy research.",
    ],
  },
  {
    id: 8,
    title: "Advanced Strategy Tips",
    duration: "3 min",
    description: "The difference between good and legendary.",
    steps: [
      "Always keep your capital well-guarded — losing it triggers a 30-tick supply crisis.",
      "Watch the global event ticker at the top — World Events can change the entire game.",
      "War Goals are secret objectives. Capture yours for +500 Gold and permanent income bonuses.",
      "Your Political Power ideology affects who will ally with you. Shared ideology = -15% ceasefire cost.",
      "In the late game, betraying an ally at the perfect moment wins championships. Timing is everything.",
    ],
  },
];

@customElement("dominion-tutorial-screen")
export class TutorialScreen extends LitElement {
  @state() private activeChapter: TutorialChapter | null = null;

  createRenderRoot() {
    return this;
  }

  render() {
    return html`
      <div
        class="flex flex-col h-full bg-dominion-bg-dark text-dominion-text-light"
        role="main"
        aria-label="Tutorial"
      >
        <header class="border-b border-dominion-border px-6 py-4">
          <h1
            class="font-display text-2xl font-bold uppercase tracking-widest text-malibu-blue"
          >
            How to Play
          </h1>
          <p class="text-sm text-dominion-text-muted">
            8 chapters covering every system
          </p>
        </header>

        <div class="flex flex-1 overflow-hidden">
          <!-- Chapter list -->
          <nav
            class="w-64 shrink-0 overflow-y-auto border-r border-dominion-border p-3 space-y-1"
            aria-label="Tutorial chapters"
          >
            ${CHAPTERS.map((ch) => this.renderChapterButton(ch))}
          </nav>

          <!-- Chapter content -->
          <div class="flex-1 overflow-y-auto p-6">
            ${this.activeChapter
              ? this.renderChapterContent(this.activeChapter)
              : html`
                  <div class="flex flex-col items-center justify-center h-full text-center gap-4">
                    <p class="text-4xl">🎖️</p>
                    <h2 class="font-bold text-xl text-dominion-text-light">
                      Welcome to Dominion.io
                    </h2>
                    <p class="text-sm text-dominion-text-muted max-w-sm">
                      Select a chapter on the left to learn how to play. Each
                      chapter builds on the last — start with Chapter 1 if
                      you're new.
                    </p>
                    <button
                      class="rounded border border-malibu-blue bg-malibu-blue/10 px-5 py-2 text-sm font-bold text-malibu-blue hover:bg-malibu-blue hover:text-dominion-bg-dark focus:outline-none focus:ring transition-colors"
                      aria-label="Start Chapter 1"
                      @click=${() => {
                        this.activeChapter = CHAPTERS[0];
                      }}
                    >
                      Start from Chapter 1
                    </button>
                  </div>
                `}
          </div>
        </div>
      </div>
    `;
  }

  private renderChapterButton(ch: TutorialChapter) {
    const isActive = this.activeChapter?.id === ch.id;
    return html`
      <button
        class=${`w-full text-left rounded px-3 py-2 text-sm transition-colors focus:outline-none focus:ring
          ${isActive ? "bg-malibu-blue/20 text-malibu-blue font-bold" : "text-dominion-text-muted hover:text-dominion-text-light hover:bg-white/5"}`}
        aria-label="Chapter ${ch.id}: ${ch.title}"
        aria-current=${isActive ? "true" : "false"}
        @click=${() => {
          this.activeChapter = ch;
        }}
      >
        <span class="block text-xs opacity-60">Ch. ${ch.id} · ${ch.duration}</span>
        ${ch.title}
      </button>
    `;
  }

  private renderChapterContent(ch: TutorialChapter) {
    const nextChapter = CHAPTERS.find((c) => c.id === ch.id + 1);
    return html`
      <div class="max-w-xl space-y-6">
        <div>
          <p class="text-xs text-dominion-text-muted uppercase tracking-widest">
            Chapter ${ch.id} · ${ch.duration}
          </p>
          <h2 class="mt-1 text-2xl font-bold text-dominion-text-light">
            ${ch.title}
          </h2>
          <p class="mt-2 text-sm text-dominion-text-muted leading-relaxed">
            ${ch.description}
          </p>
        </div>

        <ol class="space-y-3" aria-label="Chapter steps">
          ${ch.steps.map(
            (step, i) => html`
              <li class="flex gap-3">
                <span
                  class="shrink-0 w-6 h-6 rounded-full bg-malibu-blue/20 text-malibu-blue text-xs font-bold flex items-center justify-center"
                  aria-hidden="true"
                >
                  ${i + 1}
                </span>
                <span class="text-sm text-dominion-text-light leading-relaxed">
                  ${step}
                </span>
              </li>
            `,
          )}
        </ol>

        ${nextChapter
          ? html`
              <button
                class="rounded border border-dominion-border bg-dominion-bg-panel px-5 py-2 text-sm font-bold text-dominion-text-muted hover:border-malibu-blue hover:text-malibu-blue focus:outline-none focus:ring transition-colors"
                aria-label="Next chapter: ${nextChapter.title}"
                @click=${() => {
                  this.activeChapter = nextChapter;
                }}
              >
                Next: ${nextChapter.title} →
              </button>
            `
          : html`
              <div
                class="rounded border border-amber-500/30 bg-amber-500/10 p-4 text-center"
              >
                <p class="text-amber-400 font-bold">
                  🎖️ Tutorial Complete!
                </p>
                <p class="text-sm text-dominion-text-muted mt-1">
                  You're ready to play. Good luck, Commander.
                </p>
              </div>
            `}
      </div>
    `;
  }
}
