export enum FlagEra {
  AncientBC = "ancient_bc",
  ClassicalBC = "classical_bc",
  EarlyMedieval = "early_medieval",
  HighMedieval = "high_medieval",
  LateMedieval = "late_medieval",
  EarlyModern = "early_modern",
  Colonial = "colonial",
  WorldWars = "world_wars",
  ColdWar = "cold_war",
  Modern = "modern",
  Fantasy = "fantasy",
}

export enum FlagRegion {
  Europe = "europe",
  Asia = "asia",
  MiddleEast = "middle_east",
  Africa = "africa",
  Americas = "americas",
  Oceania = "oceania",
  Global = "global",
  Fantasy = "fantasy",
}

export interface FlagDefinition {
  id: string;
  name: string;
  era: FlagEra;
  region: FlagRegion;
  svgPath: string;
  historicalFact?: string;
  unlocked: true;
}

export const FLAG_ERAS_IN_ORDER: FlagEra[] = [
  FlagEra.AncientBC,
  FlagEra.ClassicalBC,
  FlagEra.EarlyMedieval,
  FlagEra.HighMedieval,
  FlagEra.LateMedieval,
  FlagEra.EarlyModern,
  FlagEra.Colonial,
  FlagEra.WorldWars,
  FlagEra.ColdWar,
  FlagEra.Modern,
  FlagEra.Fantasy,
];

export const ERA_LABELS: Record<FlagEra, string> = {
  [FlagEra.AncientBC]: "Ancient BC",
  [FlagEra.ClassicalBC]: "Classical BC",
  [FlagEra.EarlyMedieval]: "Early Medieval",
  [FlagEra.HighMedieval]: "High Medieval",
  [FlagEra.LateMedieval]: "Late Medieval",
  [FlagEra.EarlyModern]: "Early Modern",
  [FlagEra.Colonial]: "Colonial",
  [FlagEra.WorldWars]: "World Wars",
  [FlagEra.ColdWar]: "Cold War",
  [FlagEra.Modern]: "Modern",
  [FlagEra.Fantasy]: "Fantasy",
};

export const HistoricalFlags: FlagDefinition[] = [
  // ── ANCIENT BC ───────────────────────────────────────────
  {
    id: "babylonian_empire",
    name: "Babylonian Empire",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Babylonia.svg",
    historicalFact: "Babylon's Hanging Gardens were one of the Seven Wonders of the Ancient World.",
    unlocked: true,
  },
  {
    id: "assyrian_empire",
    name: "Assyrian Empire",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Assyria.svg",
    historicalFact: "Assyria built the world's first true library at Nineveh.",
    unlocked: true,
  },
  {
    id: "kingdom_of_egypt",
    name: "Kingdom of Egypt",
    era: FlagEra.AncientBC,
    region: FlagRegion.Africa,
    svgPath: "flags/Kingdom of Egypt.svg",
    historicalFact: "The Egyptian civilization lasted over 3,000 years — longer than any other.",
    unlocked: true,
  },
  {
    id: "elam",
    name: "Elam",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Elam.svg",
    historicalFact: "Elam is one of the earliest civilizations in human history.",
    unlocked: true,
  },
  {
    id: "dilmun",
    name: "Dilmun",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Dilmun.svg",
    historicalFact: "Dilmun was an ancient trading hub in the Persian Gulf.",
    unlocked: true,
  },
  {
    id: "chaldea",
    name: "Chaldea",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Chaldea.svg",
    historicalFact: "The Chaldeans were renowned astronomers who mapped the stars.",
    unlocked: true,
  },
  // ── CLASSICAL BC ─────────────────────────────────────────
  {
    id: "athenian_democracy",
    name: "Athens",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.Europe,
    svgPath: "flags/Athens.svg",
    historicalFact: "Athens invented democracy in 508 BC under Cleisthenes.",
    unlocked: true,
  },
  {
    id: "spartan_league",
    name: "Sparta",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.Europe,
    svgPath: "flags/Sparta.svg",
    historicalFact: "Spartan boys began military training at age 7.",
    unlocked: true,
  },
  {
    id: "persian_achaemenid",
    name: "Achaemenid Empire",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Achaemenid Empire.svg",
    historicalFact: "At its peak, Persia ruled 44% of the world's population.",
    unlocked: true,
  },
  {
    id: "carthage",
    name: "Carthage",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.Africa,
    svgPath: "flags/Carthage.svg",
    historicalFact: "Hannibal crossed the Alps with 37 war elephants to invade Italy.",
    unlocked: true,
  },
  {
    id: "arabia",
    name: "Arabia",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Arabia.svg",
    historicalFact: "The Arabian Peninsula was a crucial crossroads of ancient trade routes.",
    unlocked: true,
  },
  {
    id: "colchis",
    name: "Colchis",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Colchis.svg",
    historicalFact: "Colchis was the legendary home of the Golden Fleece sought by Jason and the Argonauts.",
    unlocked: true,
  },
  // ── EARLY MEDIEVAL ───────────────────────────────────────
  {
    id: "roman_empire",
    name: "West Roman Empire",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/West Roman Empire.svg",
    historicalFact: "At its peak, Rome controlled 5 million km² and 70 million people.",
    unlocked: true,
  },
  {
    id: "byzantine_empire",
    name: "Byzantine Empire",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/Byzantine Empire.svg",
    historicalFact: "The Byzantine Empire survived for over 1,000 years after Rome fell.",
    unlocked: true,
  },
  {
    id: "abbasid_caliphate",
    name: "Abbasid Caliphate",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Abbasid Caliphate.svg",
    historicalFact: "Baghdad under the Abbasids was the largest city in the world.",
    unlocked: true,
  },
  {
    id: "frankish_kingdom",
    name: "Franks",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/Franks.svg",
    historicalFact: "Charlemagne united most of Western Europe for the first time since Rome.",
    unlocked: true,
  },
  {
    id: "ethiopian_empire",
    name: "Ethiopian Empire",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.Africa,
    svgPath: "flags/Ethiopian Empire.svg",
    historicalFact: "Ethiopia is one of the oldest nations in the world with over 3,000 years of history.",
    unlocked: true,
  },
  // ── HIGH MEDIEVAL ─────────────────────────────────────────
  {
    id: "holy_roman_empire",
    name: "Holy Roman Empire",
    era: FlagEra.HighMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/Holy Roman Empire.svg",
    historicalFact: "Voltaire quipped it was 'neither holy, nor Roman, nor an empire.'",
    unlocked: true,
  },
  {
    id: "mongol_empire",
    name: "Mongol Empire",
    era: FlagEra.HighMedieval,
    region: FlagRegion.Asia,
    svgPath: "flags/Mongol Empire.svg",
    historicalFact: "The Mongol Empire was the largest contiguous land empire in history.",
    unlocked: true,
  },
  {
    id: "venice",
    name: "Venice",
    era: FlagEra.HighMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/venice.svg",
    historicalFact: "Venice was the wealthiest city in Europe and a dominant maritime power for centuries.",
    unlocked: true,
  },
  {
    id: "prussia",
    name: "Prussia",
    era: FlagEra.HighMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/prussia.svg",
    historicalFact: "Prussia's military discipline became a model for armies worldwide.",
    unlocked: true,
  },
  // ── LATE MEDIEVAL ─────────────────────────────────────────
  {
    id: "ottoman_empire",
    name: "Ottoman Empire",
    era: FlagEra.LateMedieval,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Ottoman Empire.svg",
    historicalFact: "The Ottoman Empire lasted 623 years from 1299 to 1922.",
    unlocked: true,
  },
  {
    id: "aztec_empire",
    name: "Aztec Empire",
    era: FlagEra.LateMedieval,
    region: FlagRegion.Americas,
    svgPath: "flags/Aztec Empire.svg",
    historicalFact: "Tenochtitlán was larger than any European city of its time.",
    unlocked: true,
  },
  {
    id: "qing_dynasty",
    name: "Qing Dynasty",
    era: FlagEra.LateMedieval,
    region: FlagRegion.Asia,
    svgPath: "flags/Qing Dynasty.svg",
    historicalFact: "The Qing Dynasty was the last imperial dynasty of China.",
    unlocked: true,
  },
  {
    id: "kingdom_of_portugal",
    name: "Kingdom of Portugal",
    era: FlagEra.LateMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/kingdom_of_portugal.svg",
    historicalFact: "Portugal was the first European power to establish a global maritime empire.",
    unlocked: true,
  },
  // ── EARLY MODERN ──────────────────────────────────────────
  {
    id: "spanish_empire",
    name: "Spanish Empire",
    era: FlagEra.EarlyModern,
    region: FlagRegion.Europe,
    svgPath: "flags/spanish_empire.svg",
    historicalFact: "At its peak, Spain's empire spanned the Americas, Africa, Asia, and Europe.",
    unlocked: true,
  },
  {
    id: "dutch_republic",
    name: "Dutch East India Company",
    era: FlagEra.EarlyModern,
    region: FlagRegion.Europe,
    svgPath: "flags/Dutch East India Company.svg",
    historicalFact: "The VOC was the world's first publicly traded company, valued at $8 trillion in today's money.",
    unlocked: true,
  },
  {
    id: "persia",
    name: "Persia",
    era: FlagEra.EarlyModern,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Persia.svg",
    historicalFact: "The Safavid dynasty made Persia a great power of the early modern era.",
    unlocked: true,
  },
  {
    id: "romanov_russia",
    name: "Romanov Russia",
    era: FlagEra.EarlyModern,
    region: FlagRegion.Europe,
    svgPath: "flags/Romanov Russia.svg",
    historicalFact: "The Romanov dynasty ruled Russia for 304 years before the 1917 revolution.",
    unlocked: true,
  },
  // ── COLONIAL ──────────────────────────────────────────────
  {
    id: "empire_of_japan",
    name: "Empire of Japan",
    era: FlagEra.Colonial,
    region: FlagRegion.Asia,
    svgPath: "flags/Empire of Japan.svg",
    historicalFact: "Japan transformed from a feudal society to an industrial empire in just 50 years.",
    unlocked: true,
  },
  {
    id: "confederate_states",
    name: "Confederate States",
    era: FlagEra.Colonial,
    region: FlagRegion.Americas,
    svgPath: "flags/Confederate States.svg",
    historicalFact: "The Confederacy seceded from the United States in 1861, triggering the Civil War.",
    unlocked: true,
  },
  // ── WORLD WARS ────────────────────────────────────────────
  {
    id: "soviet_union",
    name: "Soviet Union",
    era: FlagEra.WorldWars,
    region: FlagRegion.Europe,
    svgPath: "flags/ussr.svg",
    historicalFact: "The Soviet Union was the first country to put a satellite and a human in space.",
    unlocked: true,
  },
  {
    id: "imperial_japan_ww2",
    name: "Imperial Japan (WWII)",
    era: FlagEra.WorldWars,
    region: FlagRegion.Asia,
    svgPath: "flags/Empire of Japan1.svg",
    historicalFact: "Imperial Japan controlled the largest empire in Asia's history at its peak.",
    unlocked: true,
  },
  {
    id: "fascist_spain",
    name: "Fascist Spain",
    era: FlagEra.WorldWars,
    region: FlagRegion.Europe,
    svgPath: "flags/Fascist Spain.svg",
    historicalFact: "Franco's Spain remained neutral in WWII while fighting its own Civil War.",
    unlocked: true,
  },
  // ── COLD WAR ──────────────────────────────────────────────
  {
    id: "east_germany",
    name: "East Germany",
    era: FlagEra.ColdWar,
    region: FlagRegion.Europe,
    svgPath: "flags/east_germany.svg",
    historicalFact: "The Berlin Wall fell in 1989, ending the division of Germany.",
    unlocked: true,
  },
  {
    id: "west_germany",
    name: "West Germany",
    era: FlagEra.ColdWar,
    region: FlagRegion.Europe,
    svgPath: "flags/west_germany.svg",
    historicalFact: "West Germany's 'economic miracle' rebuilt the country in just two decades.",
    unlocked: true,
  },
  {
    id: "yugoslavia",
    name: "Yugoslavia",
    era: FlagEra.ColdWar,
    region: FlagRegion.Europe,
    svgPath: "flags/yugoslavia.svg",
    historicalFact: "Yugoslavia held together a diverse federation until its dissolution in the 1990s.",
    unlocked: true,
  },
  {
    id: "tibet",
    name: "Tibet",
    era: FlagEra.ColdWar,
    region: FlagRegion.Asia,
    svgPath: "flags/tibet.svg",
    historicalFact: "Tibet maintained its independence for centuries before 1950.",
    unlocked: true,
  },
  {
    id: "apartheid_south_africa",
    name: "Apartheid South Africa",
    era: FlagEra.ColdWar,
    region: FlagRegion.Africa,
    svgPath: "flags/Apartheid South Africa.svg",
    historicalFact: "South Africa's apartheid system ended in 1994 with Nelson Mandela's election.",
    unlocked: true,
  },
  // ── ANCIENT BC (additional) ───────────────────────────
  {
    id: "urartu", name: "Urartu", era: FlagEra.AncientBC, region: FlagRegion.MiddleEast,
    svgPath: "flags/Urartu.svg", historicalFact: "Urartu was the Iron Age state around Lake Van, ancestor of Armenia.", unlocked: true,
  },
  {
    id: "kingdom_of_judah", name: "Kingdom of Judah", era: FlagEra.AncientBC, region: FlagRegion.MiddleEast,
    svgPath: "flags/Kingdom of Judah.svg", historicalFact: "The Kingdom of Judah gave rise to Judaism and much of Western civilization.", unlocked: true,
  },
  {
    id: "aram_damascus", name: "Aram Damascus", era: FlagEra.AncientBC, region: FlagRegion.MiddleEast,
    svgPath: "flags/Aram Damascus.svg", historicalFact: "Damascus is one of the oldest continuously inhabited cities in the world.", unlocked: true,
  },
  {
    id: "kush", name: "Kingdom of Kush", era: FlagEra.AncientBC, region: FlagRegion.Africa,
    svgPath: "flags/Kush.svg", historicalFact: "The Kushite pharaohs ruled all of Egypt for nearly a century.", unlocked: true,
  },
  {
    id: "lydia", name: "Lydia", era: FlagEra.AncientBC, region: FlagRegion.MiddleEast,
    svgPath: "flags/Lydia.svg", historicalFact: "Lydia invented coinage — the first metal money in history.", unlocked: true,
  },
  {
    id: "phrygia", name: "Phrygia", era: FlagEra.AncientBC, region: FlagRegion.MiddleEast,
    svgPath: "flags/Phrygia.svg", historicalFact: "King Midas of Phrygia inspired the legend of the golden touch.", unlocked: true,
  },
  {
    id: "median_empire", name: "Median Empire", era: FlagEra.AncientBC, region: FlagRegion.MiddleEast,
    svgPath: "flags/Median Empire.svg", historicalFact: "The Medes allied with Babylonia to destroy the Assyrian Empire.", unlocked: true,
  },
  {
    id: "kemet", name: "Kemet", era: FlagEra.AncientBC, region: FlagRegion.Africa,
    svgPath: "flags/Kemet.svg", historicalFact: "Kemet — 'the black land' — was the ancient Egyptians' own name for their civilization.", unlocked: true,
  },
  {
    id: "saba_kingdom", name: "Kingdom of Saba", era: FlagEra.AncientBC, region: FlagRegion.MiddleEast,
    svgPath: "flags/Saba kingdom.svg", historicalFact: "The Queen of Sheba came from Saba, one of the wealthiest kingdoms of antiquity.", unlocked: true,
  },
  {
    id: "garamantes", name: "Garamantes", era: FlagEra.AncientBC, region: FlagRegion.Africa,
    svgPath: "flags/Garamant.svg", historicalFact: "The Garamantes built a vast underground irrigation network in the Sahara.", unlocked: true,
  },
  {
    id: "lihyan", name: "Lihyan", era: FlagEra.AncientBC, region: FlagRegion.MiddleEast,
    svgPath: "flags/Lihyan.svg", historicalFact: "Lihyan controlled key incense trade routes through northwest Arabia.", unlocked: true,
  },
  {
    id: "hyrcania", name: "Hyrcania", era: FlagEra.AncientBC, region: FlagRegion.MiddleEast,
    svgPath: "flags/Hyrcania.svg", historicalFact: "Hyrcania sat at the crossroads of the ancient Silk Road.", unlocked: true,
  },
  {
    id: "ancient_macedonia", name: "Macedonia", era: FlagEra.AncientBC, region: FlagRegion.Europe,
    svgPath: "flags/Macedonia.svg", historicalFact: "Alexander the Great conquered from Greece to India at age 32.", unlocked: true,
  },
  // ── CLASSICAL BC (additional) ─────────────────────────
  {
    id: "spqr", name: "Roman Republic", era: FlagEra.ClassicalBC, region: FlagRegion.Europe,
    svgPath: "flags/SPQR.svg", historicalFact: "SPQR — Senatus Populusque Romanus — the Senate and People of Rome.", unlocked: true,
  },
  {
    id: "umayyad_caliphate", name: "Umayyad Caliphate", era: FlagEra.EarlyMedieval, region: FlagRegion.MiddleEast,
    svgPath: "flags/Umayyad Caliphate.svg", historicalFact: "The Umayyad Caliphate was the largest empire the world had seen up to that point.", unlocked: true,
  },
  {
    id: "sassanid_empire", name: "Sassanid Empire", era: FlagEra.EarlyMedieval, region: FlagRegion.MiddleEast,
    svgPath: "flags/Sassanid Empire.svg", historicalFact: "The Sassanids revived Persian culture and were Rome's greatest rival for 400 years.", unlocked: true,
  },
  {
    id: "imperial_ethiopia", name: "Ethiopian Empire", era: FlagEra.EarlyMedieval, region: FlagRegion.Africa,
    svgPath: "flags/Imperial Ethiopia.svg", historicalFact: "The Ethiopian Empire traced its lineage directly to King Solomon.", unlocked: true,
  },
  // ── EARLY MEDIEVAL KINGDOMS ───────────────────────────
  {
    id: "kingdom_northumbria", name: "Northumbria", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Northumbria.svg", historicalFact: "Northumbria was the great Anglo-Saxon kingdom of northern Britain.", unlocked: true,
  },
  {
    id: "kingdom_mercia", name: "Mercia", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Mercia.svg", historicalFact: "At its peak, Mercia dominated most of England south of the Humber.", unlocked: true,
  },
  {
    id: "kingdom_wessex", name: "Wessex", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Wessex.svg", historicalFact: "King Alfred the Great of Wessex united England against the Viking invasions.", unlocked: true,
  },
  {
    id: "kingdom_east_anglia", name: "East Anglia", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_East Anglia.svg", historicalFact: "East Anglia gave England its first martyr-king, Edmund the Martyr.", unlocked: true,
  },
  {
    id: "kingdom_kent", name: "Kent", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Kent.svg", historicalFact: "Kent was the first Anglo-Saxon kingdom to convert to Christianity in 597 AD.", unlocked: true,
  },
  {
    id: "kingdom_sussex", name: "Sussex", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Sussex.svg", historicalFact: "Sussex — the kingdom of the South Saxons — was one of the Heptarchy kingdoms.", unlocked: true,
  },
  {
    id: "kingdom_essex", name: "Essex", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Essex.svg", historicalFact: "The East Saxon kingdom controlled early London before Mercia absorbed it.", unlocked: true,
  },
  {
    id: "kingdom_gwynedd", name: "Gwynedd", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Gwynedd.svg", historicalFact: "Gwynedd was the most powerful of the Welsh kingdoms throughout the medieval period.", unlocked: true,
  },
  {
    id: "kingdom_connacht", name: "Connacht", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Connacht.svg", historicalFact: "Connacht was one of the five ancient provinces of Ireland.", unlocked: true,
  },
  {
    id: "kingdom_munster", name: "Munster", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Munster.svg", historicalFact: "Brian Boru of Munster became High King of all Ireland in 1002.", unlocked: true,
  },
  {
    id: "kingdom_ulaid", name: "Ulaid", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Ulaid.svg", historicalFact: "The Ulaid of Ulster are the heroes of the ancient Irish epic the Ulster Cycle.", unlocked: true,
  },
  {
    id: "kingdom_airgialla", name: "Airgialla", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Airgialla.svg", historicalFact: "Airgialla was a federation of Irish kingdoms in what is now Ulster.", unlocked: true,
  },
  {
    id: "kingdom_dalriata", name: "Dál Riata", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Dalriata.svg", historicalFact: "Dál Riata straddled Ireland and Scotland, seeding Scottish Gaelic culture.", unlocked: true,
  },
  {
    id: "kingdom_strathclyde", name: "Strathclyde", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Strathclyde.svg", historicalFact: "Strathclyde was the last Brittonic kingdom of northern Britain.", unlocked: true,
  },
  {
    id: "kingdom_fortriu", name: "Fortriu", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Fortriu.svg", historicalFact: "Fortriu was the dominant Pictish kingdom of early medieval Scotland.", unlocked: true,
  },
  {
    id: "kingdom_dumnonia", name: "Dumnonia", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Dumnonia.svg", historicalFact: "Dumnonia in southwest Britain is associated with the legends of King Arthur.", unlocked: true,
  },
  {
    id: "kingdom_powys", name: "Powys", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Powys.svg", historicalFact: "Powys fought fiercely against Mercia for control of the Welsh marches.", unlocked: true,
  },
  {
    id: "kingdom_dyfed", name: "Dyfed", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Dyfed.svg", historicalFact: "Dyfed in southwest Wales has some of the oldest Ogham inscriptions in Britain.", unlocked: true,
  },
  {
    id: "occitania", name: "Occitania", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/1_Occitania.svg", historicalFact: "Occitania was the heartland of troubadour poetry and courtly love.", unlocked: true,
  },
  {
    id: "brittany_medieval", name: "Brittany", era: FlagEra.EarlyMedieval, region: FlagRegion.Europe,
    svgPath: "flags/brittany.svg", historicalFact: "Brittany maintained its Celtic identity long after the rest of France was Romanized.", unlocked: true,
  },
  {
    id: "normandy_medieval", name: "Normandy", era: FlagEra.HighMedieval, region: FlagRegion.Europe,
    svgPath: "flags/normandy.svg", historicalFact: "Normandy's Duke William conquered England in 1066, changing its language forever.", unlocked: true,
  },
  // ── HIGH MEDIEVAL (additional) ────────────────────────
  {
    id: "kingdom_of_jerusalem", name: "Kingdom of Jerusalem", era: FlagEra.HighMedieval, region: FlagRegion.MiddleEast,
    svgPath: "flags/Kingdom of Jerusalem.svg", historicalFact: "The Crusader Kingdom of Jerusalem lasted 88 years before Saladin retook the city.", unlocked: true,
  },
  {
    id: "castille", name: "Kingdom of Castile", era: FlagEra.HighMedieval, region: FlagRegion.Europe,
    svgPath: "flags/castille.svg", historicalFact: "Castile and Aragon's union under Ferdinand and Isabella launched the Age of Discovery.", unlocked: true,
  },
  {
    id: "sicily_kingdom", name: "Kingdom of Sicily", era: FlagEra.HighMedieval, region: FlagRegion.Europe,
    svgPath: "flags/Sicily.svg", historicalFact: "The Norman Kingdom of Sicily was the most advanced state in 12th-century Europe.", unlocked: true,
  },
  {
    id: "hafsid_caliphate", name: "Hafsid Caliphate", era: FlagEra.HighMedieval, region: FlagRegion.Africa,
    svgPath: "flags/hafsid.svg", historicalFact: "The Hafsids of Tunis controlled much of North Africa's trade for two centuries.", unlocked: true,
  },
  {
    id: "marinid_sultanate", name: "Marinid Sultanate", era: FlagEra.HighMedieval, region: FlagRegion.Africa,
    svgPath: "flags/marinid.svg", historicalFact: "The Marinids of Fez made Morocco a center of Islamic learning and architecture.", unlocked: true,
  },
  {
    id: "corsica_medieval", name: "Corsica", era: FlagEra.HighMedieval, region: FlagRegion.Europe,
    svgPath: "flags/Corsica.svg", historicalFact: "Corsica's Moor's Head flag is one of the oldest flags still in use.", unlocked: true,
  },
  {
    id: "provence_medieval", name: "Provence", era: FlagEra.HighMedieval, region: FlagRegion.Europe,
    svgPath: "flags/provence.svg", historicalFact: "Provence was a center of troubadour culture and the Counts of Barcelona.", unlocked: true,
  },
  {
    id: "flanders_medieval", name: "Flanders", era: FlagEra.HighMedieval, region: FlagRegion.Europe,
    svgPath: "flags/Flanders.svg", historicalFact: "Flanders was Europe's richest region in the 13th century due to the wool trade.", unlocked: true,
  },
  // ── LATE MEDIEVAL (additional) ────────────────────────
  {
    id: "polish_lithuanian", name: "Polish-Lithuanian Commonwealth", era: FlagEra.LateMedieval, region: FlagRegion.Europe,
    svgPath: "flags/Poland Lithuania.svg", historicalFact: "The Polish-Lithuanian Commonwealth was the largest state in 16th-century Europe.", unlocked: true,
  },
  {
    id: "habsburg_austria", name: "Habsburg Austria", era: FlagEra.LateMedieval, region: FlagRegion.Europe,
    svgPath: "flags/Habsburg Austria.svg", historicalFact: "The Habsburgs ruled the Holy Roman Empire for nearly 400 uninterrupted years.", unlocked: true,
  },
  {
    id: "kingdom_of_iraq_medieval", name: "Kingdom of Iraq", era: FlagEra.LateMedieval, region: FlagRegion.MiddleEast,
    svgPath: "flags/Kingdom of Iraq.svg", historicalFact: "The Kingdom of Iraq was established after WWI under British mandate.", unlocked: true,
  },
  {
    id: "emirate_of_asir", name: "Emirate of Asir", era: FlagEra.LateMedieval, region: FlagRegion.MiddleEast,
    svgPath: "flags/Emirate of Asir.svg", historicalFact: "The Emirate of Asir was an independent state in southwestern Arabia.", unlocked: true,
  },
  {
    id: "sultanate_of_nejd", name: "Sultanate of Nejd", era: FlagEra.LateMedieval, region: FlagRegion.MiddleEast,
    svgPath: "flags/Sultanate of Nejd.svg", historicalFact: "The Sultanate of Nejd was the precursor to modern Saudi Arabia.", unlocked: true,
  },
  // ── EARLY MODERN (additional) ─────────────────────────
  {
    id: "german_empire", name: "German Empire", era: FlagEra.EarlyModern, region: FlagRegion.Europe,
    svgPath: "flags/German Empire.svg", historicalFact: "The German Empire was proclaimed in the Hall of Mirrors at Versailles in 1871.", unlocked: true,
  },
  {
    id: "austria_hungary", name: "Austria-Hungary", era: FlagEra.EarlyModern, region: FlagRegion.Europe,
    svgPath: "flags/austria-hungary.svg", historicalFact: "Austria-Hungary was a great power of 11 nations united under one crown.", unlocked: true,
  },
  {
    id: "sweden_norway_union", name: "Sweden-Norway Union", era: FlagEra.EarlyModern, region: FlagRegion.Europe,
    svgPath: "flags/Sweden Norway Union.svg", historicalFact: "Sweden and Norway were united under one crown from 1814 until Norway's independence in 1905.", unlocked: true,
  },
  {
    id: "siam", name: "Siam", era: FlagEra.EarlyModern, region: FlagRegion.Asia,
    svgPath: "flags/Siam.svg", historicalFact: "Siam — modern Thailand — was the only Southeast Asian nation never colonized.", unlocked: true,
  },
  {
    id: "pahlavi_iran", name: "Pahlavi Iran", era: FlagEra.EarlyModern, region: FlagRegion.MiddleEast,
    svgPath: "flags/Pahlavi Iran.svg", historicalFact: "The Pahlavi dynasty modernized Iran rapidly before the 1979 revolution.", unlocked: true,
  },
  {
    id: "second_spanish_republic", name: "Second Spanish Republic", era: FlagEra.EarlyModern, region: FlagRegion.Europe,
    svgPath: "flags/Second Spanish Republic.svg", historicalFact: "The Second Republic lasted only 8 years before Franco's coup ignited civil war.", unlocked: true,
  },
  {
    id: "republic_of_formosa", name: "Republic of Formosa", era: FlagEra.EarlyModern, region: FlagRegion.Asia,
    svgPath: "flags/Republic of Formosa.svg", historicalFact: "The Republic of Formosa was history's first Asian democratic republic, lasting only 5 months.", unlocked: true,
  },
  {
    id: "far_eastern_republic", name: "Far Eastern Republic", era: FlagEra.EarlyModern, region: FlagRegion.Asia,
    svgPath: "flags/fareasternrepublic.svg", historicalFact: "The Far Eastern Republic was a buffer state between Soviet Russia and Japan, 1920–1922.", unlocked: true,
  },
  // ── COLONIAL (additional) ─────────────────────────────
  {
    id: "rhodesia", name: "Rhodesia", era: FlagEra.Colonial, region: FlagRegion.Africa,
    svgPath: "flags/Rhodesia.svg", historicalFact: "Rhodesia declared independence unilaterally in 1965, becoming a global pariah state.", unlocked: true,
  },
  {
    id: "south_vietnam", name: "South Vietnam", era: FlagEra.Colonial, region: FlagRegion.Asia,
    svgPath: "flags/South Vietnam.svg", historicalFact: "South Vietnam fell to the North in 1975, ending 20 years of war.", unlocked: true,
  },
  {
    id: "league_of_nations", name: "League of Nations", era: FlagEra.Colonial, region: FlagRegion.Global,
    svgPath: "flags/League of Nations.svg", historicalFact: "The League of Nations was the first intergovernmental peace organization, founded after WWI.", unlocked: true,
  },
  {
    id: "republic_of_china", name: "Republic of China", era: FlagEra.Colonial, region: FlagRegion.Asia,
    svgPath: "flags/Republic of China.svg", historicalFact: "The Republic of China was founded in 1912, ending 2,000 years of imperial rule.", unlocked: true,
  },
  {
    id: "danzig", name: "Free City of Danzig", era: FlagEra.Colonial, region: FlagRegion.Europe,
    svgPath: "flags/Danzig.svg", historicalFact: "Hitler's demand for Danzig was the trigger for World War II.", unlocked: true,
  },
  {
    id: "tannutuva", name: "Tannu Tuva", era: FlagEra.Colonial, region: FlagRegion.Asia,
    svgPath: "flags/tannutuva.svg", historicalFact: "Tannu Tuva was a tiny independent republic between Russia and Mongolia.", unlocked: true,
  },
  // ── WORLD WARS (additional) ───────────────────────────
  {
    id: "armenian_ssr", name: "Armenian SSR", era: FlagEra.WorldWars, region: FlagRegion.MiddleEast,
    svgPath: "flags/Armenian SSR.svg", historicalFact: "Armenia became a Soviet republic after the 1915 genocide and decades of upheaval.", unlocked: true,
  },
  {
    id: "ukrainian_ssr", name: "Ukrainian SSR", era: FlagEra.WorldWars, region: FlagRegion.Europe,
    svgPath: "flags/Ukrainian SSR.svg", historicalFact: "Ukraine suffered the Holodomor famine under Stalin, killing millions.", unlocked: true,
  },
  {
    id: "byelorussian_ssr", name: "Byelorussian SSR", era: FlagEra.WorldWars, region: FlagRegion.Europe,
    svgPath: "flags/Byelorussian SSR.svg", historicalFact: "Belarus lost a quarter of its population in World War II.", unlocked: true,
  },
  {
    id: "georgian_ssr", name: "Georgian SSR", era: FlagEra.WorldWars, region: FlagRegion.MiddleEast,
    svgPath: "flags/Georgian SSR.svg", historicalFact: "Stalin himself was born in Gori, Georgia.", unlocked: true,
  },
  {
    id: "communist_romania", name: "Communist Romania", era: FlagEra.WorldWars, region: FlagRegion.Europe,
    svgPath: "flags/Communist Romania.svg", historicalFact: "Romania's Ceaușescu was the only Eastern Bloc leader executed by firing squad.", unlocked: true,
  },
  // ── COLD WAR (additional) ─────────────────────────────
  {
    id: "libyan_jamahiriya", name: "Libyan Jamahiriya", era: FlagEra.ColdWar, region: FlagRegion.Africa,
    svgPath: "flags/Libyan Jamahiriya.svg", historicalFact: "Gaddafi's Jamahiriya was a unique 'state of the masses' with no formal government.", unlocked: true,
  },
  {
    id: "united_arab_republic", name: "United Arab Republic", era: FlagEra.ColdWar, region: FlagRegion.MiddleEast,
    svgPath: "flags/United Arab Republic.svg", historicalFact: "Egypt and Syria merged into the United Arab Republic in 1958, but it only lasted 3 years.", unlocked: true,
  },
  {
    id: "north_yemen", name: "North Yemen", era: FlagEra.ColdWar, region: FlagRegion.MiddleEast,
    svgPath: "flags/North yemen.svg", historicalFact: "North Yemen was one of the last medieval monarchies, overthrown in 1962.", unlocked: true,
  },
  {
    id: "south_yemen", name: "South Yemen", era: FlagEra.ColdWar, region: FlagRegion.MiddleEast,
    svgPath: "flags/south yemen.svg", historicalFact: "South Yemen was the only Marxist state in the Arab world.", unlocked: true,
  },
  {
    id: "zaire", name: "Zaire", era: FlagEra.ColdWar, region: FlagRegion.Africa,
    svgPath: "flags/Zaire.svg", historicalFact: "Mobutu's Zaire — now DR Congo — was one of the Cold War's most corrupt regimes.", unlocked: true,
  },
  {
    id: "burma_cold_war", name: "Burma", era: FlagEra.ColdWar, region: FlagRegion.Asia,
    svgPath: "flags/Burma.svg", historicalFact: "Burma isolated itself from the world for decades under Ne Win's military rule.", unlocked: true,
  },
  // ── MODERN NATIONS ────────────────────────────────────
  { id: "n_us", name: "United States", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/us.svg", unlocked: true },
  { id: "n_gb", name: "United Kingdom", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/gb.svg", unlocked: true },
  { id: "n_fr", name: "France", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/fr.svg", unlocked: true },
  { id: "n_de", name: "Germany", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/de.svg", unlocked: true },
  { id: "n_cn", name: "China", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/cn.svg", unlocked: true },
  { id: "n_jp", name: "Japan", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/jp.svg", unlocked: true },
  { id: "n_ru", name: "Russia", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/ru.svg", unlocked: true },
  { id: "n_in", name: "India", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/in.svg", unlocked: true },
  { id: "n_br", name: "Brazil", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/br.svg", unlocked: true },
  { id: "n_au", name: "Australia", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/au.svg", unlocked: true },
  { id: "n_ca", name: "Canada", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/ca.svg", unlocked: true },
  { id: "n_it", name: "Italy", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/it.svg", unlocked: true },
  { id: "n_es", name: "Spain", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/es.svg", unlocked: true },
  { id: "n_mx", name: "Mexico", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/mx.svg", unlocked: true },
  { id: "n_kr", name: "South Korea", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/kr.svg", unlocked: true },
  { id: "n_za", name: "South Africa", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/za.svg", unlocked: true },
  { id: "n_ng", name: "Nigeria", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ng.svg", unlocked: true },
  { id: "n_eg", name: "Egypt", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/eg.svg", unlocked: true },
  { id: "n_pk", name: "Pakistan", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/pk.svg", unlocked: true },
  { id: "n_tr", name: "Turkey", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/tr.svg", unlocked: true },
  { id: "n_ir", name: "Iran", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/ir.svg", unlocked: true },
  { id: "n_sa", name: "Saudi Arabia", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/sa.svg", unlocked: true },
  { id: "n_ar", name: "Argentina", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/ar.svg", unlocked: true },
  { id: "n_id", name: "Indonesia", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/id.svg", unlocked: true },
  { id: "n_nl", name: "Netherlands", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/nl.svg", unlocked: true },
  { id: "n_be", name: "Belgium", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/be.svg", unlocked: true },
  { id: "n_se", name: "Sweden", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/se.svg", unlocked: true },
  { id: "n_no", name: "Norway", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/no.svg", unlocked: true },
  { id: "n_fi", name: "Finland", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/fi.svg", unlocked: true },
  { id: "n_dk", name: "Denmark", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/dk.svg", unlocked: true },
  { id: "n_ch", name: "Switzerland", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/ch.svg", unlocked: true },
  { id: "n_at", name: "Austria", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/at.svg", unlocked: true },
  { id: "n_pl", name: "Poland", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/pl.svg", unlocked: true },
  { id: "n_cz", name: "Czech Republic", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/cz.svg", unlocked: true },
  { id: "n_hu", name: "Hungary", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/hu.svg", unlocked: true },
  { id: "n_ro", name: "Romania", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/ro.svg", unlocked: true },
  { id: "n_bg", name: "Bulgaria", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/bg.svg", unlocked: true },
  { id: "n_gr", name: "Greece", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/gr.svg", unlocked: true },
  { id: "n_pt", name: "Portugal", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/pt.svg", unlocked: true },
  { id: "n_ua", name: "Ukraine", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/ua.svg", unlocked: true },
  { id: "n_by", name: "Belarus", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/by.svg", unlocked: true },
  { id: "n_kz", name: "Kazakhstan", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/kz.svg", unlocked: true },
  { id: "n_ae", name: "UAE", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/ae.svg", unlocked: true },
  { id: "n_af", name: "Afghanistan", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/af.svg", unlocked: true },
  { id: "n_al", name: "Albania", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/al.svg", unlocked: true },
  { id: "n_am", name: "Armenia", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/am.svg", unlocked: true },
  { id: "n_ao", name: "Angola", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ao.svg", unlocked: true },
  { id: "n_az", name: "Azerbaijan", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/az.svg", unlocked: true },
  { id: "n_ba", name: "Bosnia & Herzegovina", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/ba.svg", unlocked: true },
  { id: "n_bd", name: "Bangladesh", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/bd.svg", unlocked: true },
  { id: "n_bf", name: "Burkina Faso", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/bf.svg", unlocked: true },
  { id: "n_bh", name: "Bahrain", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/bh.svg", unlocked: true },
  { id: "n_bi", name: "Burundi", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/bi.svg", unlocked: true },
  { id: "n_bj", name: "Benin", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/bj.svg", unlocked: true },
  { id: "n_bo", name: "Bolivia", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/bo.svg", unlocked: true },
  { id: "n_bw", name: "Botswana", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/bw.svg", unlocked: true },
  { id: "n_cd", name: "DR Congo", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/cd.svg", unlocked: true },
  { id: "n_cf", name: "Central African Republic", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/cf.svg", unlocked: true },
  { id: "n_cg", name: "Republic of Congo", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/cg.svg", unlocked: true },
  { id: "n_ci", name: "Ivory Coast", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ci.svg", unlocked: true },
  { id: "n_cl", name: "Chile", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/cl.svg", unlocked: true },
  { id: "n_cm", name: "Cameroon", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/cm.svg", unlocked: true },
  { id: "n_co", name: "Colombia", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/co.svg", unlocked: true },
  { id: "n_cr", name: "Costa Rica", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/cr.svg", unlocked: true },
  { id: "n_cu", name: "Cuba", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/cu.svg", unlocked: true },
  { id: "n_cy", name: "Cyprus", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/cy.svg", unlocked: true },
  { id: "n_dj", name: "Djibouti", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/dj.svg", unlocked: true },
  { id: "n_do", name: "Dominican Republic", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/do.svg", unlocked: true },
  { id: "n_dz", name: "Algeria", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/dz.svg", unlocked: true },
  { id: "n_ec", name: "Ecuador", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/ec.svg", unlocked: true },
  { id: "n_ee", name: "Estonia", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/ee.svg", unlocked: true },
  { id: "n_er", name: "Eritrea", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/er.svg", unlocked: true },
  { id: "n_et", name: "Ethiopia", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/et.svg", unlocked: true },
  { id: "n_fj", name: "Fiji", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/fj.svg", unlocked: true },
  { id: "n_ga", name: "Gabon", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ga.svg", unlocked: true },
  { id: "n_ge", name: "Georgia", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/ge.svg", unlocked: true },
  { id: "n_gh", name: "Ghana", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/gh.svg", unlocked: true },
  { id: "n_gn", name: "Guinea", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/gn.svg", unlocked: true },
  { id: "n_gt", name: "Guatemala", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/gt.svg", unlocked: true },
  { id: "n_gw", name: "Guinea-Bissau", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/gw.svg", unlocked: true },
  { id: "n_gy", name: "Guyana", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/gy.svg", unlocked: true },
  { id: "n_hn", name: "Honduras", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/hn.svg", unlocked: true },
  { id: "n_hr", name: "Croatia", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/hr.svg", unlocked: true },
  { id: "n_ht", name: "Haiti", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/ht.svg", unlocked: true },
  { id: "n_ie", name: "Ireland", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/ie.svg", unlocked: true },
  { id: "n_il", name: "Israel", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/il.svg", unlocked: true },
  { id: "n_iq", name: "Iraq", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/iq.svg", unlocked: true },
  { id: "n_is", name: "Iceland", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/is.svg", unlocked: true },
  { id: "n_jo", name: "Jordan", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/jo.svg", unlocked: true },
  { id: "n_ke", name: "Kenya", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ke.svg", unlocked: true },
  { id: "n_kg", name: "Kyrgyzstan", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/kg.svg", unlocked: true },
  { id: "n_kh", name: "Cambodia", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/kh.svg", unlocked: true },
  { id: "n_kp", name: "North Korea", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/kp.svg", unlocked: true },
  { id: "n_kw", name: "Kuwait", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/kw.svg", unlocked: true },
  { id: "n_la", name: "Laos", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/la.svg", unlocked: true },
  { id: "n_lb", name: "Lebanon", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/lb.svg", unlocked: true },
  { id: "n_lk", name: "Sri Lanka", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/lk.svg", unlocked: true },
  { id: "n_lr", name: "Liberia", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/lr.svg", unlocked: true },
  { id: "n_ls", name: "Lesotho", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ls.svg", unlocked: true },
  { id: "n_lt", name: "Lithuania", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/lt.svg", unlocked: true },
  { id: "n_lu", name: "Luxembourg", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/lu.svg", unlocked: true },
  { id: "n_lv", name: "Latvia", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/lv.svg", unlocked: true },
  { id: "n_ly", name: "Libya", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ly.svg", unlocked: true },
  { id: "n_ma", name: "Morocco", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ma.svg", unlocked: true },
  { id: "n_md", name: "Moldova", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/md.svg", unlocked: true },
  { id: "n_me", name: "Montenegro", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/me.svg", unlocked: true },
  { id: "n_mg", name: "Madagascar", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/mg.svg", unlocked: true },
  { id: "n_mk", name: "North Macedonia", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/mk.svg", unlocked: true },
  { id: "n_ml", name: "Mali", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ml.svg", unlocked: true },
  { id: "n_mm", name: "Myanmar", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/mm.svg", unlocked: true },
  { id: "n_mn", name: "Mongolia", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/mn.svg", unlocked: true },
  { id: "n_mr", name: "Mauritania", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/mr.svg", unlocked: true },
  { id: "n_mt", name: "Malta", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/mt.svg", unlocked: true },
  { id: "n_mu", name: "Mauritius", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/mu.svg", unlocked: true },
  { id: "n_mv", name: "Maldives", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/mv.svg", unlocked: true },
  { id: "n_mw", name: "Malawi", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/mw.svg", unlocked: true },
  { id: "n_my", name: "Malaysia", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/my.svg", unlocked: true },
  { id: "n_mz", name: "Mozambique", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/mz.svg", unlocked: true },
  { id: "n_na", name: "Namibia", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/na.svg", unlocked: true },
  { id: "n_ne", name: "Niger", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ne.svg", unlocked: true },
  { id: "n_ni", name: "Nicaragua", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/ni.svg", unlocked: true },
  { id: "n_np", name: "Nepal", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/np.svg", unlocked: true },
  { id: "n_nz", name: "New Zealand", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/nz.svg", unlocked: true },
  { id: "n_om", name: "Oman", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/om.svg", unlocked: true },
  { id: "n_pa", name: "Panama", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/pa.svg", unlocked: true },
  { id: "n_pe", name: "Peru", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/pe.svg", unlocked: true },
  { id: "n_pg", name: "Papua New Guinea", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/pg.svg", unlocked: true },
  { id: "n_ph", name: "Philippines", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/ph.svg", unlocked: true },
  { id: "n_ps", name: "Palestine", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/ps.svg", unlocked: true },
  { id: "n_qa", name: "Qatar", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/qa.svg", unlocked: true },
  { id: "n_rw", name: "Rwanda", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/rw.svg", unlocked: true },
  { id: "n_sb", name: "Solomon Islands", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/sb.svg", unlocked: true },
  { id: "n_sc", name: "Seychelles", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/sc.svg", unlocked: true },
  { id: "n_sd", name: "Sudan", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/sd.svg", unlocked: true },
  { id: "n_sg", name: "Singapore", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/sg.svg", unlocked: true },
  { id: "n_si", name: "Slovenia", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/si.svg", unlocked: true },
  { id: "n_sk", name: "Slovakia", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/sk.svg", unlocked: true },
  { id: "n_sl", name: "Sierra Leone", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/sl.svg", unlocked: true },
  { id: "n_sn", name: "Senegal", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/sn.svg", unlocked: true },
  { id: "n_so", name: "Somalia", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/so.svg", unlocked: true },
  { id: "n_sr", name: "Suriname", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/sr.svg", unlocked: true },
  { id: "n_ss", name: "South Sudan", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ss.svg", unlocked: true },
  { id: "n_sv", name: "El Salvador", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/sv.svg", unlocked: true },
  { id: "n_sy", name: "Syria", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/sy.svg", unlocked: true },
  { id: "n_td", name: "Chad", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/td.svg", unlocked: true },
  { id: "n_tg", name: "Togo", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/tg.svg", unlocked: true },
  { id: "n_th", name: "Thailand", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/th.svg", unlocked: true },
  { id: "n_tj", name: "Tajikistan", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/tj.svg", unlocked: true },
  { id: "n_tl", name: "Timor-Leste", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/tl.svg", unlocked: true },
  { id: "n_tm", name: "Turkmenistan", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/tm.svg", unlocked: true },
  { id: "n_tn", name: "Tunisia", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/tn.svg", unlocked: true },
  { id: "n_tz", name: "Tanzania", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/tz.svg", unlocked: true },
  { id: "n_ua", name: "Ukraine", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/ua.svg", unlocked: true },
  { id: "n_ug", name: "Uganda", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/ug.svg", unlocked: true },
  { id: "n_un", name: "United Nations", era: FlagEra.Modern, region: FlagRegion.Global, svgPath: "flags/un.svg", unlocked: true },
  { id: "n_uy", name: "Uruguay", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/uy.svg", unlocked: true },
  { id: "n_uz", name: "Uzbekistan", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/uz.svg", unlocked: true },
  { id: "n_va", name: "Vatican City", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/va.svg", unlocked: true },
  { id: "n_ve", name: "Venezuela", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/ve.svg", unlocked: true },
  { id: "n_vn", name: "Vietnam", era: FlagEra.Modern, region: FlagRegion.Asia, svgPath: "flags/vn.svg", unlocked: true },
  { id: "n_ye", name: "Yemen", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/ye.svg", unlocked: true },
  { id: "n_zm", name: "Zambia", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/zm.svg", unlocked: true },
  { id: "n_zw", name: "Zimbabwe", era: FlagEra.Modern, region: FlagRegion.Africa, svgPath: "flags/zw.svg", unlocked: true },
  { id: "n_eu", name: "European Union", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/eu.svg", unlocked: true },
  { id: "n_xk", name: "Kosovo", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/xk.svg", unlocked: true },
  { id: "n_rs", name: "Serbia", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/rs.svg", unlocked: true },
  { id: "n_gb_eng", name: "England", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/gb-eng.svg", unlocked: true },
  { id: "n_gb_sct", name: "Scotland", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/gb-sct.svg", unlocked: true },
  { id: "n_gb_wls", name: "Wales", era: FlagEra.Modern, region: FlagRegion.Europe, svgPath: "flags/gb-wls.svg", unlocked: true },
  { id: "n_kurdistan", name: "Kurdistan", era: FlagEra.Modern, region: FlagRegion.MiddleEast, svgPath: "flags/kurdistan.svg", unlocked: true },
  // ── US STATES ─────────────────────────────────────────
  { id: "us_al", name: "Alabama", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Alabama.svg", unlocked: true },
  { id: "us_ak", name: "Alaska", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Alaska.svg", unlocked: true },
  { id: "us_az", name: "Arizona", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Arizona.svg", unlocked: true },
  { id: "us_ar", name: "Arkansas", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Arkansas.svg", unlocked: true },
  { id: "us_ca", name: "California", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/California.svg", unlocked: true },
  { id: "us_co", name: "Colorado", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Colorado.svg", unlocked: true },
  { id: "us_ct", name: "Connecticut", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Connecticut.svg", unlocked: true },
  { id: "us_de", name: "Delaware", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Delaware.svg", unlocked: true },
  { id: "us_fl", name: "Florida", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Florida.svg", unlocked: true },
  { id: "us_ga", name: "Georgia", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Georgia_US.svg", unlocked: true },
  { id: "us_hi", name: "Hawaii", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Hawaii.svg", unlocked: true },
  { id: "us_id", name: "Idaho", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Idaho.svg", unlocked: true },
  { id: "us_il", name: "Illinois", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Illinois.svg", unlocked: true },
  { id: "us_in", name: "Indiana", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Indiana.svg", unlocked: true },
  { id: "us_ia", name: "Iowa", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Iowa.svg", unlocked: true },
  { id: "us_ks", name: "Kansas", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Kansas.svg", unlocked: true },
  { id: "us_ky", name: "Kentucky", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Kentucky.svg", unlocked: true },
  { id: "us_la", name: "Louisiana", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Louisiana.svg", unlocked: true },
  { id: "us_me", name: "Maine", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Maine.svg", unlocked: true },
  { id: "us_md", name: "Maryland", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Maryland.svg", unlocked: true },
  { id: "us_ma", name: "Massachusetts", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Massachusetts.svg", unlocked: true },
  { id: "us_mi", name: "Michigan", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Michigan.svg", unlocked: true },
  { id: "us_mn", name: "Minnesota", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Minnesota.svg", unlocked: true },
  { id: "us_ms", name: "Mississippi", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Mississippi.svg", unlocked: true },
  { id: "us_mo", name: "Missouri", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Missouri.svg", unlocked: true },
  { id: "us_mt", name: "Montana", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Montana.svg", unlocked: true },
  { id: "us_ne", name: "Nebraska", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Nebraska.svg", unlocked: true },
  { id: "us_nv", name: "Nevada", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Nevada.svg", unlocked: true },
  { id: "us_nh", name: "New Hampshire", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/New_Hampshire.svg", unlocked: true },
  { id: "us_nj", name: "New Jersey", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/New_Jersey.svg", unlocked: true },
  { id: "us_nm", name: "New Mexico", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/New_Mexico.svg", unlocked: true },
  { id: "us_ny", name: "New York", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/New_York.svg", unlocked: true },
  { id: "us_nc", name: "North Carolina", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/North_Carolina.svg", unlocked: true },
  { id: "us_nd", name: "North Dakota", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/North_Dakota.svg", unlocked: true },
  { id: "us_oh", name: "Ohio", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Ohio.svg", unlocked: true },
  { id: "us_ok", name: "Oklahoma", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Oklahoma.svg", unlocked: true },
  { id: "us_or", name: "Oregon", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Oregon.svg", unlocked: true },
  { id: "us_pa", name: "Pennsylvania", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Pennsylvania.svg", unlocked: true },
  { id: "us_ri", name: "Rhode Island", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Rhode_Island.svg", unlocked: true },
  { id: "us_sc", name: "South Carolina", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/South_Carolina.svg", unlocked: true },
  { id: "us_sd", name: "South Dakota", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/South_Dakota.svg", unlocked: true },
  { id: "us_tn", name: "Tennessee", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Tennessee.svg", unlocked: true },
  { id: "us_tx", name: "Texas", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Texas.svg", unlocked: true },
  { id: "us_ut", name: "Utah", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Utah.svg", unlocked: true },
  { id: "us_vt", name: "Vermont", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Vermont.svg", unlocked: true },
  { id: "us_va", name: "Virginia", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Virginia.svg", unlocked: true },
  { id: "us_wa", name: "Washington", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Washington.svg", unlocked: true },
  { id: "us_wv", name: "West Virginia", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/West_Virginia.svg", unlocked: true },
  { id: "us_wi", name: "Wisconsin", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Wisconsin.svg", unlocked: true },
  { id: "us_wy", name: "Wyoming", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Wyoming.svg", unlocked: true },
  { id: "us_dc", name: "Washington D.C.", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/District_of_Columbia.svg", unlocked: true },
  // ── CANADIAN PROVINCES ────────────────────────────────
  { id: "ca_ab", name: "Alberta", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/alberta.svg", unlocked: true },
  { id: "ca_bc", name: "British Columbia", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/britishcolumbia.svg", unlocked: true },
  { id: "ca_mb", name: "Manitoba", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/manitoba.svg", unlocked: true },
  { id: "ca_nb", name: "New Brunswick", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/ca_nb.svg", unlocked: true },
  { id: "ca_nl", name: "Newfoundland & Labrador", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/newfoundlandandlabrador.svg", unlocked: true },
  { id: "ca_nt", name: "Northwest Territories", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/northwestterritories.svg", unlocked: true },
  { id: "ca_ns", name: "Nova Scotia", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/ca_ns.svg", unlocked: true },
  { id: "ca_nu", name: "Nunavut", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Nunavut.svg", unlocked: true },
  { id: "ca_on", name: "Ontario", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/ontario.svg", unlocked: true },
  { id: "ca_pe", name: "Prince Edward Island", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/princeedwardisland.svg", unlocked: true },
  { id: "ca_qc", name: "Quebec", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Quebec.svg", unlocked: true },
  { id: "ca_sk", name: "Saskatchewan", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/saskatchewan.svg", unlocked: true },
  { id: "ca_yt", name: "Yukon", era: FlagEra.Modern, region: FlagRegion.Americas, svgPath: "flags/Yukon.svg", unlocked: true },
  // ── AUSTRALIAN STATES ─────────────────────────────────
  { id: "au_nt", name: "Northern Territory", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/aus_norter.svg", unlocked: true },
  { id: "au_nsw", name: "New South Wales", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/aus_nsw.svg", unlocked: true },
  { id: "au_qld", name: "Queensland", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/aus_quelan.svg", unlocked: true },
  { id: "au_sa", name: "South Australia", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/aus_souaus.svg", unlocked: true },
  { id: "au_tas", name: "Tasmania", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/aus_tas.svg", unlocked: true },
  { id: "au_vic", name: "Victoria", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/aus_vic.svg", unlocked: true },
  { id: "au_wa", name: "Western Australia", era: FlagEra.Modern, region: FlagRegion.Oceania, svgPath: "flags/aus_wesaus.svg", unlocked: true },
  // ── SPECIAL / CULTURAL ────────────────────────────────
  {
    id: "amazigh", name: "Amazigh (Berber)", era: FlagEra.Fantasy, region: FlagRegion.Africa,
    svgPath: "flags/Amazigh flag.svg", historicalFact: "The Amazigh are the indigenous people of North Africa, predating Arab conquest by millennia.", unlocked: true,
  },
  {
    id: "australian_aboriginal", name: "Aboriginal Australia", era: FlagEra.Fantasy, region: FlagRegion.Oceania,
    svgPath: "flags/Australian Aboriginal Flag.svg", historicalFact: "Aboriginal Australians have the world's oldest continuous cultural tradition — over 65,000 years.", unlocked: true,
  },
  {
    id: "maori", name: "Māori", era: FlagEra.Fantasy, region: FlagRegion.Oceania,
    svgPath: "flags/Maori flag.svg", historicalFact: "The Māori navigated thousands of miles of open ocean to settle New Zealand.", unlocked: true,
  },
  {
    id: "sami", name: "Sami People", era: FlagEra.Fantasy, region: FlagRegion.Europe,
    svgPath: "flags/Sami flag.svg", historicalFact: "The Sami are the indigenous people of the Scandinavian Arctic, reindeer herders for millennia.", unlocked: true,
  },
  {
    id: "alkebulan", name: "Alkebulan", era: FlagEra.Fantasy, region: FlagRegion.Africa,
    svgPath: "flags/Alkebulan.svg", historicalFact: "Alkebulan — 'mother of mankind' — is an ancient name for Africa used before European colonization.", unlocked: true,
  },
  {
    id: "toki_pona", name: "Toki Pona Nation", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/toki_pona.svg", historicalFact: "Toki Pona is a constructed language with only 137 words, designed around minimalism.", unlocked: true,
  },
  {
    id: "socialist_flag", name: "The Workers' Front", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/Socialist_flag.svg", historicalFact: "The red flag of international socialism has flown over revolutions across five continents.", unlocked: true,
  },
  {
    id: "liberalism_flag", name: "Liberal Republic", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/Liberalism_flag.svg", historicalFact: "Liberty, equality, and the rule of law — the eternal ideals of the liberal tradition.", unlocked: true,
  },
  {
    id: "capybara_nation", name: "Capybara Nation", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/Capybara.svg", historicalFact: "The most chill nation on earth. No wars. Just vibes and rivers.", unlocked: true,
  },
  {
    id: "kiwi_republic", name: "Kiwi Republic", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/Kiwi.svg", historicalFact: "Flightless birds make surprisingly effective commanders.", unlocked: true,
  },
  {
    id: "baguette_empire", name: "Baguette Empire", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/baguette.svg", historicalFact: "An empire built on bread, wine, and an inexplicable sense of cultural superiority.", unlocked: true,
  },
  {
    id: "sardines_confederation", name: "Sardine Confederation", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/sardines.svg", historicalFact: "Small, silver, packed in tight — but united they are unstoppable.", unlocked: true,
  },
  {
    id: "santa_claus_dominion", name: "Santa's Dominion", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/santa_claus.svg", historicalFact: "Controls the North Pole. Logistics empire. Naughty list is classified.", unlocked: true,
  },
  {
    id: "listenbourg", name: "Republic of Listenbourg", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/Listenbourg.svg", historicalFact: "Listenbourg was 'discovered' in 2022 as an internet meme country — and now has its own flag.", unlocked: true,
  },
  {
    id: "white_flag", name: "White Flag", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/White Flag.svg", historicalFact: "Unconditional surrender has never looked so clean.", unlocked: true,
  },
  {
    id: "ror_empire", name: "RoR Empire", era: FlagEra.Fantasy, region: FlagRegion.Fantasy,
    svgPath: "flags/Ror Empire.svg", historicalFact: "The legendary empire that never loses — according to its own historians.", unlocked: true,
  },
  // ── FANTASY ───────────────────────────────────────────────
  {
    id: "pirate_republic",
    name: "Republic of Pirates",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/Republic of Pirates.svg",
    historicalFact: "No king, no law, no quarter — only the wind and the sea.",
    unlocked: true,
  },
  {
    id: "anarchist",
    name: "Anarchist Federation",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/Anarchist flag.svg",
    historicalFact: "Where no rulers reign and every citizen commands.",
    unlocked: true,
  },
  {
    id: "cthulhu_republic",
    name: "Cthulhu Republic",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/Cthulhu Republic.svg",
    historicalFact: "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn.",
    unlocked: true,
  },
  {
    id: "communist_flag",
    name: "People's Collective",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/Communist flag.svg",
    historicalFact: "Workers of the world, unite!",
    unlocked: true,
  },
  {
    id: "frost_giant",
    name: "Frost Giants",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/frost_giant.svg",
    historicalFact: "They march from the frozen north, unstoppable as the glacier.",
    unlocked: true,
  },
  {
    id: "polar_bears",
    name: "Arctic Dominion",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/polar_bears.svg",
    historicalFact: "The last sovereign nation of the frozen north.",
    unlocked: true,
  },
];

export const TerritoryThemes = [
  { id: "olive_green", name: "Olive Green", color: "#4A5C3A" },
  { id: "desert_tan", name: "Desert Tan", color: "#C4A882" },
  { id: "navy_blue", name: "Navy Blue", color: "#1B2A4A" },
  { id: "crimson_red", name: "Crimson Red", color: "#8B1A1A" },
  { id: "steel_grey", name: "Steel Grey", color: "#5A6472" },
  { id: "royal_purple", name: "Royal Purple", color: "#4B0082" },
  { id: "imperial_gold", name: "Imperial Gold", color: "#C8973A" },
  { id: "byzantine_blue", name: "Byzantine Blue", color: "#1E3A6E" },
  { id: "sakura_rose", name: "Sakura Rose", color: "#E8A0B0" },
  { id: "nile_gold", name: "Nile Gold", color: "#D4A843" },
  { id: "dragon_black", name: "Dragon Black", color: "#1A1A2E" },
  { id: "elven_silver", name: "Elven Silver", color: "#C0C8D0" },
  { id: "infernal_red", name: "Infernal Red", color: "#FF2200" },
  { id: "frost_blue", name: "Frost Blue", color: "#A8D8EA" },
  { id: "shadow_void", name: "Shadow Void", color: "#0D0D1A" },
] as const;

export type TerritoryTheme = (typeof TerritoryThemes)[number];

export function flagsByEra(era: FlagEra): FlagDefinition[] {
  return HistoricalFlags.filter((f) => f.era === era);
}

export function searchFlags(query: string): FlagDefinition[] {
  const q = query.toLowerCase();
  return HistoricalFlags.filter(
    (f) =>
      f.name.toLowerCase().includes(q) ||
      f.era.includes(q) ||
      f.region.includes(q),
  );
}
