export enum FlagEra {
  AncientBC = "ancient_bc",
  ClassicalBC = "classical_bc",
  EarlyMedieval = "early_medieval",
  HighMedieval = "high_medieval",
  LateMedieval = "late_medieval",
  EarlyModern = "early_modern",
  Colonial = "colonial",
  WorldWars = "world_wars",
  ColdWar = "cold_war",
  Modern = "modern",
  Fantasy = "fantasy",
}

export enum FlagRegion {
  Europe = "europe",
  Asia = "asia",
  MiddleEast = "middle_east",
  Africa = "africa",
  Americas = "americas",
  Oceania = "oceania",
  Global = "global",
  Fantasy = "fantasy",
}

export interface FlagDefinition {
  id: string;
  name: string;
  era: FlagEra;
  region: FlagRegion;
  svgPath: string;
  historicalFact?: string;
  unlocked: true;
}

export const FLAG_ERAS_IN_ORDER: FlagEra[] = [
  FlagEra.AncientBC,
  FlagEra.ClassicalBC,
  FlagEra.EarlyMedieval,
  FlagEra.HighMedieval,
  FlagEra.LateMedieval,
  FlagEra.EarlyModern,
  FlagEra.Colonial,
  FlagEra.WorldWars,
  FlagEra.ColdWar,
  FlagEra.Modern,
  FlagEra.Fantasy,
];

export const ERA_LABELS: Record<FlagEra, string> = {
  [FlagEra.AncientBC]: "Ancient BC",
  [FlagEra.ClassicalBC]: "Classical BC",
  [FlagEra.EarlyMedieval]: "Early Medieval",
  [FlagEra.HighMedieval]: "High Medieval",
  [FlagEra.LateMedieval]: "Late Medieval",
  [FlagEra.EarlyModern]: "Early Modern",
  [FlagEra.Colonial]: "Colonial",
  [FlagEra.WorldWars]: "World Wars",
  [FlagEra.ColdWar]: "Cold War",
  [FlagEra.Modern]: "Modern",
  [FlagEra.Fantasy]: "Fantasy",
};

export const HistoricalFlags: FlagDefinition[] = [
  // ── ANCIENT BC ───────────────────────────────────────────
  {
    id: "babylonian_empire",
    name: "Babylonian Empire",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Babylonia.svg",
    historicalFact: "Babylon's Hanging Gardens were one of the Seven Wonders of the Ancient World.",
    unlocked: true,
  },
  {
    id: "assyrian_empire",
    name: "Assyrian Empire",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Assyria.svg",
    historicalFact: "Assyria built the world's first true library at Nineveh.",
    unlocked: true,
  },
  {
    id: "kingdom_of_egypt",
    name: "Kingdom of Egypt",
    era: FlagEra.AncientBC,
    region: FlagRegion.Africa,
    svgPath: "flags/Kingdom of Egypt.svg",
    historicalFact: "The Egyptian civilization lasted over 3,000 years — longer than any other.",
    unlocked: true,
  },
  {
    id: "elam",
    name: "Elam",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Elam.svg",
    historicalFact: "Elam is one of the earliest civilizations in human history.",
    unlocked: true,
  },
  {
    id: "dilmun",
    name: "Dilmun",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Dilmun.svg",
    historicalFact: "Dilmun was an ancient trading hub in the Persian Gulf.",
    unlocked: true,
  },
  {
    id: "chaldea",
    name: "Chaldea",
    era: FlagEra.AncientBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Chaldea.svg",
    historicalFact: "The Chaldeans were renowned astronomers who mapped the stars.",
    unlocked: true,
  },
  // ── CLASSICAL BC ─────────────────────────────────────────
  {
    id: "athenian_democracy",
    name: "Athens",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.Europe,
    svgPath: "flags/Athens.svg",
    historicalFact: "Athens invented democracy in 508 BC under Cleisthenes.",
    unlocked: true,
  },
  {
    id: "spartan_league",
    name: "Sparta",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.Europe,
    svgPath: "flags/Sparta.svg",
    historicalFact: "Spartan boys began military training at age 7.",
    unlocked: true,
  },
  {
    id: "persian_achaemenid",
    name: "Achaemenid Empire",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Achaemenid Empire.svg",
    historicalFact: "At its peak, Persia ruled 44% of the world's population.",
    unlocked: true,
  },
  {
    id: "carthage",
    name: "Carthage",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.Africa,
    svgPath: "flags/Carthage.svg",
    historicalFact: "Hannibal crossed the Alps with 37 war elephants to invade Italy.",
    unlocked: true,
  },
  {
    id: "arabia",
    name: "Arabia",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Arabia.svg",
    historicalFact: "The Arabian Peninsula was a crucial crossroads of ancient trade routes.",
    unlocked: true,
  },
  {
    id: "colchis",
    name: "Colchis",
    era: FlagEra.ClassicalBC,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Colchis.svg",
    historicalFact: "Colchis was the legendary home of the Golden Fleece sought by Jason and the Argonauts.",
    unlocked: true,
  },
  // ── EARLY MEDIEVAL ───────────────────────────────────────
  {
    id: "roman_empire",
    name: "West Roman Empire",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/West Roman Empire.svg",
    historicalFact: "At its peak, Rome controlled 5 million km² and 70 million people.",
    unlocked: true,
  },
  {
    id: "byzantine_empire",
    name: "Byzantine Empire",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/Byzantine Empire.svg",
    historicalFact: "The Byzantine Empire survived for over 1,000 years after Rome fell.",
    unlocked: true,
  },
  {
    id: "abbasid_caliphate",
    name: "Abbasid Caliphate",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Abbasid Caliphate.svg",
    historicalFact: "Baghdad under the Abbasids was the largest city in the world.",
    unlocked: true,
  },
  {
    id: "frankish_kingdom",
    name: "Franks",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/Franks.svg",
    historicalFact: "Charlemagne united most of Western Europe for the first time since Rome.",
    unlocked: true,
  },
  {
    id: "ethiopian_empire",
    name: "Ethiopian Empire",
    era: FlagEra.EarlyMedieval,
    region: FlagRegion.Africa,
    svgPath: "flags/Ethiopian Empire.svg",
    historicalFact: "Ethiopia is one of the oldest nations in the world with over 3,000 years of history.",
    unlocked: true,
  },
  // ── HIGH MEDIEVAL ─────────────────────────────────────────
  {
    id: "holy_roman_empire",
    name: "Holy Roman Empire",
    era: FlagEra.HighMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/Holy Roman Empire.svg",
    historicalFact: "Voltaire quipped it was 'neither holy, nor Roman, nor an empire.'",
    unlocked: true,
  },
  {
    id: "mongol_empire",
    name: "Mongol Empire",
    era: FlagEra.HighMedieval,
    region: FlagRegion.Asia,
    svgPath: "flags/Mongol Empire.svg",
    historicalFact: "The Mongol Empire was the largest contiguous land empire in history.",
    unlocked: true,
  },
  {
    id: "venice",
    name: "Venice",
    era: FlagEra.HighMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/venice.svg",
    historicalFact: "Venice was the wealthiest city in Europe and a dominant maritime power for centuries.",
    unlocked: true,
  },
  {
    id: "prussia",
    name: "Prussia",
    era: FlagEra.HighMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/prussia.svg",
    historicalFact: "Prussia's military discipline became a model for armies worldwide.",
    unlocked: true,
  },
  // ── LATE MEDIEVAL ─────────────────────────────────────────
  {
    id: "ottoman_empire",
    name: "Ottoman Empire",
    era: FlagEra.LateMedieval,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Ottoman Empire.svg",
    historicalFact: "The Ottoman Empire lasted 623 years from 1299 to 1922.",
    unlocked: true,
  },
  {
    id: "aztec_empire",
    name: "Aztec Empire",
    era: FlagEra.LateMedieval,
    region: FlagRegion.Americas,
    svgPath: "flags/Aztec Empire.svg",
    historicalFact: "Tenochtitlán was larger than any European city of its time.",
    unlocked: true,
  },
  {
    id: "qing_dynasty",
    name: "Qing Dynasty",
    era: FlagEra.LateMedieval,
    region: FlagRegion.Asia,
    svgPath: "flags/Qing Dynasty.svg",
    historicalFact: "The Qing Dynasty was the last imperial dynasty of China.",
    unlocked: true,
  },
  {
    id: "kingdom_of_portugal",
    name: "Kingdom of Portugal",
    era: FlagEra.LateMedieval,
    region: FlagRegion.Europe,
    svgPath: "flags/kingdom_of_portugal.svg",
    historicalFact: "Portugal was the first European power to establish a global maritime empire.",
    unlocked: true,
  },
  // ── EARLY MODERN ──────────────────────────────────────────
  {
    id: "spanish_empire",
    name: "Spanish Empire",
    era: FlagEra.EarlyModern,
    region: FlagRegion.Europe,
    svgPath: "flags/spanish_empire.svg",
    historicalFact: "At its peak, Spain's empire spanned the Americas, Africa, Asia, and Europe.",
    unlocked: true,
  },
  {
    id: "dutch_republic",
    name: "Dutch East India Company",
    era: FlagEra.EarlyModern,
    region: FlagRegion.Europe,
    svgPath: "flags/Dutch East India Company.svg",
    historicalFact: "The VOC was the world's first publicly traded company, valued at $8 trillion in today's money.",
    unlocked: true,
  },
  {
    id: "persia",
    name: "Persia",
    era: FlagEra.EarlyModern,
    region: FlagRegion.MiddleEast,
    svgPath: "flags/Persia.svg",
    historicalFact: "The Safavid dynasty made Persia a great power of the early modern era.",
    unlocked: true,
  },
  {
    id: "romanov_russia",
    name: "Romanov Russia",
    era: FlagEra.EarlyModern,
    region: FlagRegion.Europe,
    svgPath: "flags/Romanov Russia.svg",
    historicalFact: "The Romanov dynasty ruled Russia for 304 years before the 1917 revolution.",
    unlocked: true,
  },
  // ── COLONIAL ──────────────────────────────────────────────
  {
    id: "empire_of_japan",
    name: "Empire of Japan",
    era: FlagEra.Colonial,
    region: FlagRegion.Asia,
    svgPath: "flags/Empire of Japan.svg",
    historicalFact: "Japan transformed from a feudal society to an industrial empire in just 50 years.",
    unlocked: true,
  },
  {
    id: "confederate_states",
    name: "Confederate States",
    era: FlagEra.Colonial,
    region: FlagRegion.Americas,
    svgPath: "flags/Confederate States.svg",
    historicalFact: "The Confederacy seceded from the United States in 1861, triggering the Civil War.",
    unlocked: true,
  },
  // ── WORLD WARS ────────────────────────────────────────────
  {
    id: "soviet_union",
    name: "Soviet Union",
    era: FlagEra.WorldWars,
    region: FlagRegion.Europe,
    svgPath: "flags/ussr.svg",
    historicalFact: "The Soviet Union was the first country to put a satellite and a human in space.",
    unlocked: true,
  },
  {
    id: "imperial_japan_ww2",
    name: "Imperial Japan (WWII)",
    era: FlagEra.WorldWars,
    region: FlagRegion.Asia,
    svgPath: "flags/Empire of Japan1.svg",
    historicalFact: "Imperial Japan controlled the largest empire in Asia's history at its peak.",
    unlocked: true,
  },
  {
    id: "fascist_spain",
    name: "Fascist Spain",
    era: FlagEra.WorldWars,
    region: FlagRegion.Europe,
    svgPath: "flags/Fascist Spain.svg",
    historicalFact: "Franco's Spain remained neutral in WWII while fighting its own Civil War.",
    unlocked: true,
  },
  // ── COLD WAR ──────────────────────────────────────────────
  {
    id: "east_germany",
    name: "East Germany",
    era: FlagEra.ColdWar,
    region: FlagRegion.Europe,
    svgPath: "flags/east_germany.svg",
    historicalFact: "The Berlin Wall fell in 1989, ending the division of Germany.",
    unlocked: true,
  },
  {
    id: "west_germany",
    name: "West Germany",
    era: FlagEra.ColdWar,
    region: FlagRegion.Europe,
    svgPath: "flags/west_germany.svg",
    historicalFact: "West Germany's 'economic miracle' rebuilt the country in just two decades.",
    unlocked: true,
  },
  {
    id: "yugoslavia",
    name: "Yugoslavia",
    era: FlagEra.ColdWar,
    region: FlagRegion.Europe,
    svgPath: "flags/yugoslavia.svg",
    historicalFact: "Yugoslavia held together a diverse federation until its dissolution in the 1990s.",
    unlocked: true,
  },
  {
    id: "tibet",
    name: "Tibet",
    era: FlagEra.ColdWar,
    region: FlagRegion.Asia,
    svgPath: "flags/tibet.svg",
    historicalFact: "Tibet maintained its independence for centuries before 1950.",
    unlocked: true,
  },
  {
    id: "apartheid_south_africa",
    name: "Apartheid South Africa",
    era: FlagEra.ColdWar,
    region: FlagRegion.Africa,
    svgPath: "flags/Apartheid South Africa.svg",
    historicalFact: "South Africa's apartheid system ended in 1994 with Nelson Mandela's election.",
    unlocked: true,
  },
  // ── FANTASY ───────────────────────────────────────────────
  {
    id: "pirate_republic",
    name: "Republic of Pirates",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/Republic of Pirates.svg",
    historicalFact: "No king, no law, no quarter — only the wind and the sea.",
    unlocked: true,
  },
  {
    id: "anarchist",
    name: "Anarchist Federation",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/Anarchist flag.svg",
    historicalFact: "Where no rulers reign and every citizen commands.",
    unlocked: true,
  },
  {
    id: "cthulhu_republic",
    name: "Cthulhu Republic",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/Cthulhu Republic.svg",
    historicalFact: "Ph'nglui mglw'nafh Cthulhu R'lyeh wgah'nagl fhtagn.",
    unlocked: true,
  },
  {
    id: "communist_flag",
    name: "People's Collective",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/Communist flag.svg",
    historicalFact: "Workers of the world, unite!",
    unlocked: true,
  },
  {
    id: "frost_giant",
    name: "Frost Giants",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/frost_giant.svg",
    historicalFact: "They march from the frozen north, unstoppable as the glacier.",
    unlocked: true,
  },
  {
    id: "polar_bears",
    name: "Arctic Dominion",
    era: FlagEra.Fantasy,
    region: FlagRegion.Fantasy,
    svgPath: "flags/polar_bears.svg",
    historicalFact: "The last sovereign nation of the frozen north.",
    unlocked: true,
  },
];

export const TerritoryThemes = [
  { id: "olive_green", name: "Olive Green", color: "#4A5C3A" },
  { id: "desert_tan", name: "Desert Tan", color: "#C4A882" },
  { id: "navy_blue", name: "Navy Blue", color: "#1B2A4A" },
  { id: "crimson_red", name: "Crimson Red", color: "#8B1A1A" },
  { id: "steel_grey", name: "Steel Grey", color: "#5A6472" },
  { id: "royal_purple", name: "Royal Purple", color: "#4B0082" },
  { id: "imperial_gold", name: "Imperial Gold", color: "#C8973A" },
  { id: "byzantine_blue", name: "Byzantine Blue", color: "#1E3A6E" },
  { id: "sakura_rose", name: "Sakura Rose", color: "#E8A0B0" },
  { id: "nile_gold", name: "Nile Gold", color: "#D4A843" },
  { id: "dragon_black", name: "Dragon Black", color: "#1A1A2E" },
  { id: "elven_silver", name: "Elven Silver", color: "#C0C8D0" },
  { id: "infernal_red", name: "Infernal Red", color: "#FF2200" },
  { id: "frost_blue", name: "Frost Blue", color: "#A8D8EA" },
  { id: "shadow_void", name: "Shadow Void", color: "#0D0D1A" },
] as const;

export type TerritoryTheme = (typeof TerritoryThemes)[number];

export function flagsByEra(era: FlagEra): FlagDefinition[] {
  return HistoricalFlags.filter((f) => f.era === era);
}

export function searchFlags(query: string): FlagDefinition[] {
  const q = query.toLowerCase();
  return HistoricalFlags.filter(
    (f) =>
      f.name.toLowerCase().includes(q) ||
      f.era.includes(q) ||
      f.region.includes(q),
  );
}
